config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tweets#index"

  # resources :relationships, only: [:index, :toggle_relationship]
  get 'relationships', to: 'relationships#index'
  post 'relationships', to: 'relationships#toggle_relationship'

  post 'tweets/:id/likes', to: 'tweets#likes', as: :likes
  delete 'tweets/:id/likes', to: 'tweets#undo_likes', as: :undo_likes

  resources :tweets do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates :body, presence: true

  default_scope { order(created_at: :desc) }
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :body, presence: true, length: {:maximum => 140}

  default_scope { order(created_at: :desc) }

  belongs_to :user
  has_many :comments, dependent: :destroy

  acts_as_likeable

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
  has_many :comments

  validates :name, presence: true

  default_scope { order(name: :asc) }

  has_many :following_relationships,  class_name: "UserRelationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers_relationships, class_name: "UserRelationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :following_relationships, source: :followed
  has_many :followers, through: :followers_relationships, source: :follower

  acts_as_liker

  def following?(other_user)
    following.include?(other_user)
  end

  def follow(other_user)
    following_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    following_relationships.find_by(followed_id: other_user.id).destroy
  end

  def twitter_feed
    following_ids = "SELECT followed_id FROM user_relationships WHERE  follower_id = ?"
    Tweet.where("user_id IN (#{following_ids}) OR user_id = ?", id, id)
  end

end

app/models/user_relationship.rb
class UserRelationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from ActiveRecord::RecordNotFound, with: :resource_not_found

  protected

    def resource_not_found
    end

    def configure_permitted_parameters
      added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_tweet, only: [ :create ]

  def create
    unless current_user
      flash.now[:alert] = "You need to sign in or sign up before continuing."
      redirect_to new_user_session_path
    else
      @comment = @tweet.comments.build(comment_params)
      @comment.user = current_user

      if @comment.save
        flash[:notice] = "Comment has been added."
      else
        flash.now[:alert] = "Comment has not been added."
      end
      redirect_to tweet_path(@tweet)
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:body)
    end

    def set_tweet
      @tweet = Tweet.find(params[:tweet_id])
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def index
    @users = User.where("id != ?", current_user.id)
  end

  def toggle_relationship
    success = false
    msg_start = ""
    other_user = User.find(params["other_user_id"])
    if other_user
      if current_user.following?(other_user)
        current_user.unfollow(other_user)
        msg_start = "Unfollowing"
      else
        current_user.follow(other_user)
        msg_start = "Following"
      end
      success = true
    end
    if success
      render status: 200, json: {
        message: "#{msg_start} #{other_user.name} Succeeded"
      }.to_json
    else
      render status: 422, json: {
        message: "#{msg_start} Failed"
      }.to_json
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [ :show, :edit, :update, :destroy, :likes, :undo_likes ]
  before_action :authenticate_user!, except: [ :show, :index ]

  def index
    if current_user
      @tweets = current_user.twitter_feed.paginate(:page => params[:page], :per_page => 3)
    end
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    if @tweet.save
      flash[:success] = "Tweet has been posted"
      redirect_to tweets_path
    else
      flash.now[:danger] = "Tweet has not been posted"
      render :new
    end
  end

  def show
    @comment = @tweet.comments.build # for the new one
    @comments = @tweet.comments
  end

  def edit
    unless @tweet.user == current_user
      flash[:alert] = "You can only edit your own tweets."
      redirect_to root_path
    end
  end

  def update
    unless @tweet.user == current_user
      flash[:alert] = "You can only edit your own tweets."
      redirect_to root_path
    else
      if @tweet.update(tweet_params)
        flash[:success] = "Tweet has been updated"
        redirect_to @tweet
      else
        flash.now[:danger] = "Tweet has not been updated"
        render :edit
      end
    end
  end

  def destroy
    unless @tweet.user == current_user
      flash[:alert] = "You can only delete your own tweets."
      redirect_to root_path
    else
      if @tweet.destroy
        flash[:success] = "Tweet has been deleted."
        redirect_to tweets_path
      end
    end
  end

  def likes
    current_user.like!(@tweet)
    flash[:success] = "Tweet has been Liked"
    redirect_to root_path
  end

  def undo_likes
    current_user.unlike!(@tweet)
    flash[:success] = "Tweet has been unliked"
    redirect_to root_path
  end

  protected

    def resource_not_found
      flash[:alert] = "The tweet you are looking for could not be found"
      redirect_to root_path
    end

  private

    def tweet_params
      params.require(:tweet).permit(:body)
    end

    def set_tweet
      @tweet = Tweet.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def persisted_comments(comments)
    comments.reject{ |comment| comment.new_record? }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header"%>

    <%= render "shared/main_body"%>
  </body>
</html>

app/views/relationships/_user.html.erb
<div class="row">
  <div class="well well-lg">
    <div class="row">
      <div class="col-md-4">
        <%= user.name %>
      </div>
      <div class="col-md-4">
        <%= pluralize(user.tweets.count, "tweet") %> posted
      </div>
      <div class="col-md-4">
        <% btn_value = current_user.following?(user) ? "Unfollow" : "Follow" %>
        <button type="button" id="follow-<%= user.id %>" class="follow-btn btn btn-primary pull-right" data-dismiss="modal" data-id="<%= user.id %>"><%= btn_value %></button>
      </div>
    </div>
  </div>
</div>

app/views/relationships/index.html.erb
<h3 class="text-center">Who To Follow/Unfollow</h3>

<% if @users.empty? %>
  <h1 id="no-user">No Users to Follow</h1>
<% else %>
  <div id="toggle-followers">
    <% @users.each do |user| %>
      <%= render "user", { :user => user } %>
    <% end %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header role="banner">
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Twitter Clone", root_path, class: "navbar-brand" %>
      </div>
      <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li><%= link_to "Follow", relationships_path %></li>
            <p class="navbar-text">
              Signed in as <%= "#{current_user.email}" %>
            </p>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_main_body.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% flash.each do |key, message| %>
        <div class="text-center alert alert-<%= key == 'notice'? 'success': 'danger' %>">
        <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </div>
</div>

app/views/tweets/_comment.html.erb
<div class="comment-body">
  <%= comment.body %>
</div>
<div class="comment-time">
  <%= time_ago_in_words(comment.created_at) %>
  ago by <%= comment.user.email %>
</div>
<hr />

app/views/tweets/_form.html.erb
<div class="row">
  <div class="col-md-12">

  <%= form_for( @tweet, :html => {class: "form-horizontal", role: "form"} ) do |f| %>
    <% if @tweet.errors.any? %>
      <div class="panel panel-danger col-md-offset-1">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(@tweet.errors.count, "error") %>
            prohibited this tweet from being posted:
          </h2>
          <div class="panel-body">
            <ul>
              <% @tweet.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>

    <div class="form-group">
      <div class="control-label col-md-offset-1 col-md-1">
        <%= f.label :body %>
      </div>
      <div class="col-md-10">
        <%= f.text_area :body, rows: 1, class: 'form-control', maxlength: 140, placeholder: 'Body of Tweet', autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <%= f.submit "Post", class: 'btn btn-primary btn-lg pull-right' %>
      </div>
    </div>
  <% end %>

  </div>
</div>

app/views/tweets/edit.html.erb
<h3 class="text-center">Edit Tweet</h3>

<%= render 'form' %>

app/views/tweets/index.html.erb
<% if user_signed_in? %>
  <%= link_to "New Tweet", new_tweet_path, class: "btn btn-default btn-lg", id: "new-tweet-btn" %>
<% end %>

<% if @tweets %>
  <h1 id="no-tweets">Your Feed</h1>
  <%= will_paginate @tweets %>
  <% @tweets.each do |tweet| %>
    <div class="well well-lg">
      <div class="tweet-body">
        <%= link_to tweet.body, tweet_path(tweet) %>
      </div>
      <div class="author">
        <small>
          Created by: <%= tweet.user.name %> (<%= tweet.user.email %>) on <%= tweet.created_at.strftime("%b %d %Y") %>
        </small>
      </div>
      <div class="likes_count">
        <%= tweet.likers_count %> Likes
      </div>
      <div class="pull-right">
        <% if tweet.liked_by?(current_user) %>
          <%= link_to 'Undo like', undo_likes_path(tweet), :method => :delete, :class => 'btn btn-primary btn-xs' %>
        <% else %>
          <%= link_to 'Like', likes_path(tweet), :method => :post, :class => 'btn btn-primary btn-xs' %>
        <% end %>
      </div>
    </div>
  <% end %>
  <%= will_paginate @tweets %>
<% else %>
  <h1 id="no-tweets">No Tweets in Your Feed</h1>
  <p>Create a tweet and follow others<p>
<% end %>

app/views/tweets/new.html.erb
<h3 class="text-center">Add new Tweet</h3>

<%= render 'form' %>

app/views/tweets/show.html.erb
<article class="detail-tweet">

  <div class="tweet-body">
    <%= @tweet.body %>
  </div>
  <div class="tweet-date">
    <%= @tweet.created_at.strftime("%b %d %Y") %>
  </div>

  <% if user_signed_in? && current_user == @tweet.user %>
    <div class="edit-delete">
      <%= link_to "Edit Tweet", edit_tweet_path(@tweet), class: "btn btn-primary btn-lg btn-space" %>
      <%= link_to "Delete Tweet", tweet_path(@tweet), method: :delete,
        data: { confirm: "Are you sure you want to delete this tweet?" }, class: "btn btn-primary btn-lg btn-space" %>
    </div>
  <% end %>
</article>

<hr>

<div class="col-md-12">
<%  #remote: true,%>
  <%= form_for [@tweet, @comment],
        :html => {class: "form-horizontal", role: "form"} do |f| %>

    <% if @comment.errors.any? %>
      <div class="panel panel-danger col-md-offset-1">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(@comment.errors.count, "error") %>
            prohibited this comment from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% @comment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>

    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :body, "New Comment" %>
      </div>
      <div class="col-md-10">
        <%= f.text_area :body, rows: 10, class: "form-control", placeholder: "Your comments" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-1 col-md-11">
        <%= f.submit "Add Comment", class: 'btn btn-primary btn-lg pull-right' %>
      </div>
    </div>

  <% end %>
</div>

<div class="col-md-12">
  <header>
    <h2>Comments</h2>
  </header>
  <div class="col-md-10">
    <% if @tweet.comments.any? %>
      <div id="messages">
        <% persisted_comments(@comments).each do |comment| %>
          <%= render 'comment', { :comment => comment } %>
        <% end %>
      </div>
    <% else %>
      There are no comments to show.
    <% end %>
  </div>
</div>